# Generated by Django 5.2.12 on 2026-03-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="resumes/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("extracted_text", models.TextField(blank=True)),
                ("skills", models.JSONField(default=list)),
                ("experience_years", models.FloatField(default=0)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("feedback", models.JSONField(default=dict)),
                ("score", models.IntegerField(default=0)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("harvard", "Harvard"),
                            ("google", "Google"),
                            ("minimal", "Minimal"),
                        ],
                        default="harvard",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("job_description", models.TextField()),
                ("match_score", models.IntegerField(default=0)),
                ("matching_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("ai_analysis", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("summary", "Professional Summary"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("certifications", "Certifications"),
                            ("links", "Links & Profiles"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
