# Generated by Django 5.2.12 on 2026-03-15 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("target_titles", models.JSONField(default=list)),
                (
                    "remote_preference",
                    models.CharField(
                        choices=[
                            ("remote", "Remote only"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                            ("flexible", "Any / flexible"),
                        ],
                        default="remote",
                        max_length=20,
                    ),
                ),
                ("min_salary", models.IntegerField(default=60000)),
                ("max_experience_years", models.IntegerField(default=4)),
                ("known_skills", models.JSONField(default=list)),
                ("skill_levels", models.JSONField(default=dict)),
                (
                    "experience_years",
                    models.CharField(
                        choices=[
                            ("0", "No professional experience"),
                            ("0-1", "Less than 1 year"),
                            ("1-2", "1–2 years"),
                            ("2-4", "2–4 years"),
                            ("4+", "4+ years"),
                        ],
                        default="0-1",
                        max_length=10,
                    ),
                ),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("projects_summary", models.TextField(blank=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("current_step", models.CharField(default="welcome", max_length=20)),
                ("onboarding_started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "onboarding_assessment_level",
                    models.CharField(blank=True, max_length=20),
                ),
                ("onboarding_assessment_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
